OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, s0;
opaque UHdg a0, s0;
opaque cUH c, a0, s0;
opaque cUHdg c, a0, s0;
opaque mcx selector, c0, t;

qreg q[5];

// q[0] = Hamiltonian-simulation selector ancilla
// q[1] = QSP imaginary-part extraction selector ancilla
// q[2] = QSP phase ancilla
// q[3] = block-encoding ancilla[0]
// q[4] = system qubit[0]

// Full Hamiltonian simulation QSP block generated by tools/hamsim_qsp.py.
// The outer selector multiplexes the QSP phases: each common layer applies the
// cosine signed phase, then selector |1> adds the sine-cosine phase difference.
// The common U_H/U_Hdg skeleton is shared; only the sine branch has the final
// extra U_H and phase. The component selector extracts pyqsp's imaginary
// response before the outer sdg+h combines P_cos(H) - i P_sin(H).
//
// P_cos(x) = 0.49983892707908911 - 0.061208046917365276*x^2
// P_sin(x) = 0.24995964765863563*x - 0.010254919978348976*x^3
// Expected all-zero selector branch = 0.24991946353954456 - 0.12497982382931781*i*x - 0.030604023458682638*x^2 + 0.005127459989174488*i*x^3
//
// QSP phases:
//   cos phi_0 = -0.017334547212187006
//   cos phi_1 = 0.48874370016932378
//   cos phi_2 = -0.017334547212187006
//   sin phi_0 = -0.0013012427794075725
//   sin phi_1 = 0.12233209296437383
//   sin phi_2 = 0.12233209296437383
//   sin phi_3 = -0.0013012427794075725

h q[0];
h q[1];

// common phase 0
// cos phi_0 = -0.0173345472122
// cos psi_0 = 0.768063616185
// sin phi_0 = -0.00130124277941
// sin psi_0 = 0.784096920618
// Delta_0 = sin psi_0 - cos psi_0 = 0.0160333044328
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(0.768063616185) q[2];
cx q[3], q[2];
rz(-0.768063616185) q[2];
cx q[3], q[2];
x q[3];

rz(-0.768063616185) q[2];
cx q[3], q[2];
rz(0.768063616185) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.0160333044328) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.0160333044328) q[2];

mcx q[0], q[1], q[2];

rz(0.0160333044328) q[2];

mcx q[0], q[1], q[2];

rz(-0.0160333044328) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U
UH q[3], q[4];

// common phase 1
// cos phi_1 = 0.488743700169
// cos psi_1 = 2.05954002696
// sin phi_1 = 0.122332092964
// sin psi_1 = 1.69312841976
// Delta_1 = sin psi_1 - cos psi_1 = -0.366411607205
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(2.05954002696) q[2];
cx q[3], q[2];
rz(-2.05954002696) q[2];
cx q[3], q[2];
x q[3];

rz(-2.05954002696) q[2];
cx q[3], q[2];
rz(2.05954002696) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.366411607205) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.366411607205) q[2];

mcx q[0], q[1], q[2];

rz(-0.366411607205) q[2];

mcx q[0], q[1], q[2];

rz(0.366411607205) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U^\dagger
UHdg q[3], q[4];

// common phase 2
// cos phi_2 = -0.0173345472122
// cos psi_2 = 0.768063616185
// sin phi_2 = 0.122332092964
// sin psi_2 = 1.69312841976
// Delta_2 = sin psi_2 - cos psi_2 = 0.925064803574
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(0.768063616185) q[2];
cx q[3], q[2];
rz(-0.768063616185) q[2];
cx q[3], q[2];
x q[3];

rz(-0.768063616185) q[2];
cx q[3], q[2];
rz(0.768063616185) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.925064803574) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.925064803574) q[2];

mcx q[0], q[1], q[2];

rz(0.925064803574) q[2];

mcx q[0], q[1], q[2];

rz(-0.925064803574) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// sin-only final U
cUH q[0], q[3], q[4];

// final sin-only phase 3
// sin phi_3 = -0.00130124277941
// sin psi_3 = -0.786699406177
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.786699406177) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.786699406177) q[2];

mcx q[0], q[1], q[2];

rz(-0.786699406177) q[2];

mcx q[0], q[1], q[2];

rz(0.786699406177) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// extract pyqsp imaginary response on the component selector
h q[1];
s q[1];
x q[1];

// combine 1/2 * (E_cos - i E_sin)
sdg q[0];
h q[0];
