OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, a1, s0;
opaque UHdg a0, a1, s0;
opaque mcx c0, c1, t;

qreg q[5];

// q[0] = phase ancilla
// q[1] = block-encoding ancilla[0]
// q[2] = block-encoding ancilla[1]
// q[3] = selector ancilla
// q[4] = system qubit[0]

// Selector-wrapped Hamiltonian simulation cos component.
// Generated by tools/hamsim_qsp.py with:
//   tau = 0.5
//   epsilon = 0.0001
//   method = sym_qsp
//   signal_operator = Wx
//   ensure_bounded = True
//   scale = 0.5
//
// The base QSP component has Im B[00] = P_cos(H). The selector wrapper
// coherently runs theta and -theta branches, takes their difference, multiplies
// by -i, and moves the result to the all-zero selector branch. Therefore the
// final all-zero branch is directly P_cos(H), so the verifier compares
// the full polynomial.
//
// Open-control multi-controlled X gates on the block ancillas are expanded
// with x gates around abstract mcx. This matches the paper convention that
// phases act on the |0...0> block-ancilla branch.
//
// P_cos(x) = 0.49999966355545339 - 0.062493938728279574*x^2 + 0.0012858918109143005*x^4
//
// QSP phases:
//   phi_0 = 9.1052521925845284e-05
//   phi_1 = -0.017336228154365477
//   phi_2 = 0.48874382575306075
//   phi_3 = -0.017336228154365477
//   phi_4 = 9.1052521925845284e-05
//
// Physical OpenQASM rz angles use theta_rz = -2 * psi:
//   theta_0 = -1.5709784318387483
//   theta_1 = -3.1069201972810623
//   theta_2 = -4.1190803050959151
//   theta_3 = -3.1069201972810623
//   theta_4 = -1.5709784318387483

h q[3];

// phi_0 = 9.10525219258e-05
// psi_0 = 0.785489215919
// solid-control theta_0 = -1.57097843184
// open-control SELECT_RZ theta_0 = 1.57097843184
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(0.785489215919) q[0];
cx q[3], q[0];
rz(-0.785489215919) q[0];
cx q[3], q[0];
x q[3];
rz(-0.785489215919) q[0];
cx q[3], q[0];
rz(0.785489215919) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U
UH q[1], q[2], q[4];

// phi_1 = -0.0173362281544
// psi_1 = 1.55346009864
// solid-control theta_1 = -3.10692019728
// open-control SELECT_RZ theta_1 = 3.10692019728
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.55346009864) q[0];
cx q[3], q[0];
rz(-1.55346009864) q[0];
cx q[3], q[0];
x q[3];
rz(-1.55346009864) q[0];
cx q[3], q[0];
rz(1.55346009864) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U^\dagger
UHdg q[1], q[2], q[4];

// phi_2 = 0.488743825753
// psi_2 = 2.05954015255
// solid-control theta_2 = -4.1190803051
// open-control SELECT_RZ theta_2 = 4.1190803051
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(2.05954015255) q[0];
cx q[3], q[0];
rz(-2.05954015255) q[0];
cx q[3], q[0];
x q[3];
rz(-2.05954015255) q[0];
cx q[3], q[0];
rz(2.05954015255) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U
UH q[1], q[2], q[4];

// phi_3 = -0.0173362281544
// psi_3 = 1.55346009864
// solid-control theta_3 = -3.10692019728
// open-control SELECT_RZ theta_3 = 3.10692019728
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.55346009864) q[0];
cx q[3], q[0];
rz(-1.55346009864) q[0];
cx q[3], q[0];
x q[3];
rz(-1.55346009864) q[0];
cx q[3], q[0];
rz(1.55346009864) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U^\dagger
UHdg q[1], q[2], q[4];

// phi_4 = 9.10525219258e-05
// psi_4 = 0.785489215919
// solid-control theta_4 = -1.57097843184
// open-control SELECT_RZ theta_4 = 1.57097843184
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(0.785489215919) q[0];
cx q[3], q[0];
rz(-0.785489215919) q[0];
cx q[3], q[0];
x q[3];
rz(-0.785489215919) q[0];
cx q[3], q[0];
rz(0.785489215919) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

h q[3];
sdg q[3];
x q[3];
