OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, a1, s0;
opaque UHdg a0, a1, s0;
opaque mcx c0, c1, t;

qreg q[5];

// q[0] = phase ancilla
// q[1] = block-encoding ancilla[0]
// q[2] = block-encoding ancilla[1]
// q[3] = selector ancilla
// q[4] = system qubit[0]

// Selector-wrapped Hamiltonian simulation sin component.
// Generated by tools/hamsim_qsp.py with:
//   tau = 0.5
//   epsilon = 0.0001
//   method = sym_qsp
//   signal_operator = Wx
//   ensure_bounded = True
//   scale = 0.5
//
// The base QSP component has Im B[00] = P_sin(H). The selector wrapper
// coherently runs theta and -theta branches, takes their difference, multiplies
// by -i, and moves the result to the all-zero selector branch. Therefore the
// final all-zero branch is directly P_sin(H), so the verifier compares
// the full polynomial.
//
// Open-control multi-controlled X gates on the block ancillas are expanded
// with x gates around abstract mcx. This matches the paper convention that
// phases act on the |0...0> block-ancilla branch.
//
// P_sin(x) = 0.24999991579484243*x - 0.010415992523176125*x^3 + 0.00012885803586171963*x^5
//
// QSP phases:
//   phi_0 = 4.0876887309541981e-06
//   phi_1 = -0.0013011822987092736
//   phi_2 = 0.1223320925366167
//   phi_3 = 0.1223320925366167
//   phi_4 = -0.0013011822987092736
//   phi_5 = 4.0876887309541981e-06
//
// Physical OpenQASM rz angles use theta_rz = -2 * psi:
//   theta_0 = -1.5708045021723585
//   theta_1 = -3.1389902889923746
//   theta_2 = -3.3862568386630265
//   theta_3 = -3.3862568386630265
//   theta_4 = -3.1389902889923746
//   theta_5 = 1.5707881514174347

h q[3];

// phi_0 = 4.08768873095e-06
// psi_0 = 0.785402251086
// solid-control theta_0 = -1.57080450217
// open-control SELECT_RZ theta_0 = 1.57080450217
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(0.785402251086) q[0];
cx q[3], q[0];
rz(-0.785402251086) q[0];
cx q[3], q[0];
x q[3];
rz(-0.785402251086) q[0];
cx q[3], q[0];
rz(0.785402251086) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U
UH q[1], q[2], q[4];

// phi_1 = -0.00130118229871
// psi_1 = 1.5694951445
// solid-control theta_1 = -3.13899028899
// open-control SELECT_RZ theta_1 = 3.13899028899
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.5694951445) q[0];
cx q[3], q[0];
rz(-1.5694951445) q[0];
cx q[3], q[0];
x q[3];
rz(-1.5694951445) q[0];
cx q[3], q[0];
rz(1.5694951445) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U^\dagger
UHdg q[1], q[2], q[4];

// phi_2 = 0.122332092537
// psi_2 = 1.69312841933
// solid-control theta_2 = -3.38625683866
// open-control SELECT_RZ theta_2 = 3.38625683866
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.69312841933) q[0];
cx q[3], q[0];
rz(-1.69312841933) q[0];
cx q[3], q[0];
x q[3];
rz(-1.69312841933) q[0];
cx q[3], q[0];
rz(1.69312841933) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U
UH q[1], q[2], q[4];

// phi_3 = 0.122332092537
// psi_3 = 1.69312841933
// solid-control theta_3 = -3.38625683866
// open-control SELECT_RZ theta_3 = 3.38625683866
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.69312841933) q[0];
cx q[3], q[0];
rz(-1.69312841933) q[0];
cx q[3], q[0];
x q[3];
rz(-1.69312841933) q[0];
cx q[3], q[0];
rz(1.69312841933) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U^\dagger
UHdg q[1], q[2], q[4];

// phi_4 = -0.00130118229871
// psi_4 = 1.5694951445
// solid-control theta_4 = -3.13899028899
// open-control SELECT_RZ theta_4 = 3.13899028899
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(1.5694951445) q[0];
cx q[3], q[0];
rz(-1.5694951445) q[0];
cx q[3], q[0];
x q[3];
rz(-1.5694951445) q[0];
cx q[3], q[0];
rz(1.5694951445) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

// U
UH q[1], q[2], q[4];

// phi_5 = 4.08768873095e-06
// psi_5 = -0.785394075709
// solid-control theta_5 = 1.57078815142
// open-control SELECT_RZ theta_5 = -1.57078815142
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];
x q[3];
rz(-0.785394075709) q[0];
cx q[3], q[0];
rz(0.785394075709) q[0];
cx q[3], q[0];
x q[3];
rz(0.785394075709) q[0];
cx q[3], q[0];
rz(-0.785394075709) q[0];
cx q[3], q[0];
x q[1];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[1];

h q[3];
sdg q[3];
x q[3];
