OPENQASM 2.0;
include "qelib1.inc";

opaque UH a, s;
opaque UHdg a, s;

qreg q[3];

// q[0] = phase ancilla
// q[1] = block-encoding ancilla
// q[2] = system qubit

// Hamiltonian simulation QSP sine component generated by:
// python3 tools/hamsim_qsp.py --tau 0.5 --epsilon 1e-4 --component sin
//
// pyqsp settings:
//   method = sym_qsp
//   signal_operator = Wx
//   ensure_bounded = True
//   scale = 0.5
//   tau = 0.5
//   epsilon = 1e-4
//   pyqsp_response_part = imag
//
// Target polynomial in monomial basis:
// P_sin(x) =
//   0.24999991579484243 x
// - 0.010415992523176125 x^3
// + 0.00012885803586171963 x^5
//
// This approximates 0.5 * sin(0.5 x).
// QSP phases:
//   phi_0 = 0.000004087688730954198
//   phi_1 = -0.0013011822987092736
//   phi_2 = 0.1223320925366167
//   phi_3 = 0.1223320925366167
//   phi_4 = -0.0013011822987092736
//   phi_5 = 0.000004087688730954198
//
// QSVT projector phases after Wx -> real-embedding conversion:
//   psi_0 = phi_0 + pi/4 = 0.7854022510861792
//   psi_1 = phi_1 + pi/2 = 1.5694951444961873
//   psi_2 = phi_2 + pi/2 = 1.6931284193315133
//   psi_3 = phi_3 + pi/2 = 1.6931284193315133
//   psi_4 = phi_4 + pi/2 = 1.5694951444961873
//   psi_5 = phi_5 - pi/4 = -0.7853940757087173
//
// Physical OpenQASM rz angles use theta_rz = -2 * psi:
//   theta_0 = -1.5708045021723585
//   theta_1 = -3.1389902889923746
//   theta_2 = -3.3862568386630265
//   theta_3 = -3.3862568386630265
//   theta_4 = -3.1389902889923746
//   theta_5 = 1.5707881514174347

// phi_0, psi_0, theta_0
h q[0];
cz q[0], q[1];
h q[0];
rz(-1.5708045021723585) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U
UH q[1], q[2];

// phi_1, psi_1, theta_1
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.1389902889923746) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U^\dagger
UHdg q[1], q[2];

// phi_2, psi_2, theta_2
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.3862568386630265) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U
UH q[1], q[2];

// phi_3, psi_3, theta_3
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.3862568386630265) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U^\dagger
UHdg q[1], q[2];

// phi_4, psi_4, theta_4
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.1389902889923746) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U
UH q[1], q[2];

// phi_5, psi_5, theta_5
h q[0];
cz q[0], q[1];
h q[0];
rz(1.5707881514174347) q[0];
h q[0];
cz q[0], q[1];
h q[0];
