OPENQASM 2.0;
include "qelib1.inc";

opaque UH a, s;
opaque UHdg a, s;

qreg q[3];

// q[0] = phase ancilla
// q[1] = block-encoding ancilla
// q[2] = system qubit

// Hamiltonian simulation QSP cosine component generated by:
// python3 tools/hamsim_qsp.py --tau 0.5 --epsilon 1e-4 --component cos
//
// pyqsp settings:
//   method = sym_qsp
//   signal_operator = Wx
//   ensure_bounded = True
//   scale = 0.5
//   tau = 0.5
//   epsilon = 1e-4
//   pyqsp_response_part = imag
//
// Target polynomial in monomial basis:
// P_cos(x) =
//   0.4999996635554534
// - 0.062493938728279574 x^2
// + 0.0012858918109143005 x^4
//
// This approximates 0.5 * cos(0.5 x).
// QSP phases:
//   phi_0 = 0.00009105252192584528
//   phi_1 = -0.017336228154365477
//   phi_2 = 0.48874382575306075
//   phi_3 = -0.017336228154365477
//   phi_4 = 0.00009105252192584528
//
// QSVT projector phases after Wx -> real-embedding conversion:
//   psi_0 = phi_0 + pi/4 = 0.7854892159193742
//   psi_1 = phi_1 + pi/2 = 1.5534600986405311
//   psi_2 = phi_2 + pi/2 = 2.0595401525479575
//   psi_3 = phi_3 + pi/2 = 1.5534600986405311
//   psi_4 = phi_4 + pi/4 = 0.7854892159193742
//
// Physical OpenQASM rz angles use theta_rz = -2 * psi:
//   theta_0 = -1.5709784318387483
//   theta_1 = -3.1069201972810623
//   theta_2 = -4.119080305095915
//   theta_3 = -3.1069201972810623
//   theta_4 = -1.5709784318387483

// phi_0, psi_0, theta_0
h q[0];
cz q[0], q[1];
h q[0];
rz(-1.5709784318387483) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U
UH q[1], q[2];

// phi_1, psi_1, theta_1
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.1069201972810623) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U^\dagger
UHdg q[1], q[2];

// phi_2, psi_2, theta_2
h q[0];
cz q[0], q[1];
h q[0];
rz(-4.119080305095915) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U
UH q[1], q[2];

// phi_3, psi_3, theta_3
h q[0];
cz q[0], q[1];
h q[0];
rz(-3.1069201972810623) q[0];
h q[0];
cz q[0], q[1];
h q[0];

// U^\dagger
UHdg q[1], q[2];

// phi_4, psi_4, theta_4
h q[0];
cz q[0], q[1];
h q[0];
rz(-1.5709784318387483) q[0];
h q[0];
cz q[0], q[1];
h q[0];
