OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, s0;
opaque UHdg a0, s0;
opaque cUH c, a0, s0;
opaque cUHdg c, a0, s0;
opaque mcx c0, t;

qreg q[4];

// q[0] = phase ancilla
// q[1] = block-encoding ancilla[0]
// q[2] = selector ancilla
// q[3] = system qubit[0]

// Selector-wrapped Hamiltonian simulation cos component.
// Generated by tools/hamsim_qsp.py with:
//   tau = 0.5
//   epsilon = 0.0001
//   method = sym_qsp
//   signal_operator = Wx
//   ensure_bounded = True
//   scale = 0.5
//
// The base QSP component has Im B[00] = P_cos(H). The selector wrapper
// runs C on selector |0> and the true adjoint C^dagger on selector |1>, then
// extracts (C - C^dagger)/(2i). Therefore the final all-zero branch is directly
// P_cos(H), so the verifier compares the full polynomial.
//
// Open-control multi-controlled X gates on the block ancillas are expanded
// with x gates around abstract mcx. This matches the paper convention that
// phases act on the |0...0> block-ancilla branch.
//
// P_cos(x) = 0.49999966355545339 - 0.062493938728279574*x^2 + 0.0012858918109143005*x^4
//
// QSP phases:
//   phi_0 = 9.1052521925845284e-05
//   phi_1 = -0.017336228154365477
//   phi_2 = 0.48874382575306075
//   phi_3 = -0.017336228154365477
//   phi_4 = 9.1052521925845284e-05
//
// Physical OpenQASM rz angles use theta_rz = -2 * psi:
//   theta_0 = -1.5709784318387483
//   theta_1 = -3.1069201972810623
//   theta_2 = -4.1190803050959151
//   theta_3 = -3.1069201972810623
//   theta_4 = -1.5709784318387483

h q[2];

// C branch: selector = 0
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[2], q[0];
x q[2];
rz(-0.785489215919) q[0];
x q[2];
mcx q[2], q[0];
x q[2];
rz(0.785489215919) q[0];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
cUH q[2], q[1], q[3];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[2], q[0];
x q[2];
rz(-1.55346009864) q[0];
x q[2];
mcx q[2], q[0];
x q[2];
rz(1.55346009864) q[0];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
cUHdg q[2], q[1], q[3];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[2], q[0];
x q[2];
rz(-2.05954015255) q[0];
x q[2];
mcx q[2], q[0];
x q[2];
rz(2.05954015255) q[0];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
cUH q[2], q[1], q[3];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[2], q[0];
x q[2];
rz(-1.55346009864) q[0];
x q[2];
mcx q[2], q[0];
x q[2];
rz(1.55346009864) q[0];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
cUHdg q[2], q[1], q[3];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[2], q[0];
x q[2];
rz(-0.785489215919) q[0];
x q[2];
mcx q[2], q[0];
x q[2];
rz(0.785489215919) q[0];
x q[2];
cx q[2], q[1];
x q[2];
x q[2];
mcx q[1], q[2], q[0];
x q[2];
x q[2];
cx q[2], q[1];
x q[2];

// Cdag branch: selector = 1
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
mcx q[2], q[0];
rz(0.785489215919) q[0];
mcx q[2], q[0];
rz(-0.785489215919) q[0];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
cUH q[2], q[1], q[3];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
mcx q[2], q[0];
rz(1.55346009864) q[0];
mcx q[2], q[0];
rz(-1.55346009864) q[0];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
cUHdg q[2], q[1], q[3];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
mcx q[2], q[0];
rz(2.05954015255) q[0];
mcx q[2], q[0];
rz(-2.05954015255) q[0];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
cUH q[2], q[1], q[3];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
mcx q[2], q[0];
rz(1.55346009864) q[0];
mcx q[2], q[0];
rz(-1.55346009864) q[0];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
cUHdg q[2], q[1], q[3];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];
mcx q[2], q[0];
rz(0.785489215919) q[0];
mcx q[2], q[0];
rz(-0.785489215919) q[0];
cx q[2], q[1];
mcx q[2], q[1], q[0];
cx q[2], q[1];

z q[2];
h q[2];
rz(3.14159265359) q[2];
