OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, s0;
opaque UHdg a0, s0;
opaque cUH c, a0, s0;
opaque cUHdg c, a0, s0;
opaque ccUH c0, c1, a0, s0;
opaque ccUHdg c0, c1, a0, s0;
opaque mcx selector, c0, t;

qreg q[5];

// q[0] = Hamiltonian-simulation selector ancilla
// q[1] = QSP imaginary-part extraction selector ancilla
// q[2] = QSP phase ancilla
// q[3] = block-encoding ancilla[0]
// q[4] = system qubit[0]

// Full Hamiltonian simulation QSP block generated by tools/hamsim_qsp.py.
// Example verification base: H = (X + Y + Z)/3.
// The QASM remains an abstract UH/UHdg block encoding; pass the base to
// symbolic.verify with --base '(X + Y + Z)/3'.
// The component selector extracts each raw pyqsp response as
// (C - C^dagger)/(2i), using a true reverse-order adjoint branch. The outer
// selector then combines the extracted components as
// 1/2 * (P_cos(H) - i P_sin(H)).
//
// P_cos(x) = 0.49983892707908911 - 0.061208046917365276*x^2
// P_sin(x) = 0.24995964765863563*x - 0.010254919978348976*x^3
// Expected all-zero selector branch = 0.24991946353954456 - 0.12497982382931781*i*x - 0.030604023458682638*x^2 + 0.005127459989174488*i*x^3
//
// QSP phases:
//   cos phi_0 = -0.017334547212187006
//   cos phi_1 = 0.48874370016932378
//   cos phi_2 = -0.017334547212187006
//   sin phi_0 = -0.0013012427794075725
//   sin phi_1 = 0.12233209296437383
//   sin phi_2 = 0.12233209296437383
//   sin phi_3 = -0.0013012427794075725

h q[0];
h q[1];

// cos C branch: selector = 0, component selector = 0
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(-0.768063616185) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(0.768063616185) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
ccUH q[0], q[1], q[3], q[4];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(-2.05954002696) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(2.05954002696) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
ccUHdg q[0], q[1], q[3], q[4];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(-0.768063616185) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[2];
x q[1];
x q[0];
rz(0.768063616185) q[2];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[3], q[0], q[1], q[2];
x q[1];
x q[0];
x q[0];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[0];

// cos Cdag branch: selector = 0, component selector = 1
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(0.768063616185) q[2];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(-0.768063616185) q[2];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
ccUH q[1], q[0], q[3], q[4];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(2.05954002696) q[2];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(-2.05954002696) q[2];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
ccUHdg q[1], q[0], q[3], q[4];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(0.768063616185) q[2];
x q[0];
mcx q[0], q[1], q[2];
x q[0];
rz(-0.768063616185) q[2];
x q[0];
mcx q[1], q[0], q[3];
x q[0];
x q[0];
mcx q[1], q[3], q[0], q[2];
x q[0];
x q[0];
mcx q[1], q[0], q[3];
x q[0];

// sin C branch: selector = 1, component selector = 0
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(-0.784096920618) q[2];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(0.784096920618) q[2];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
ccUH q[0], q[1], q[3], q[4];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(-1.69312841976) q[2];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(1.69312841976) q[2];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
ccUHdg q[0], q[1], q[3], q[4];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(-1.69312841976) q[2];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(1.69312841976) q[2];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
ccUH q[0], q[1], q[3], q[4];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(0.786699406177) q[2];
x q[1];
mcx q[1], q[0], q[2];
x q[1];
rz(-0.786699406177) q[2];
x q[1];
mcx q[0], q[1], q[3];
x q[1];
x q[1];
mcx q[0], q[3], q[1], q[2];
x q[1];
x q[1];
mcx q[0], q[1], q[3];
x q[1];

// sin Cdag branch: selector = 1, component selector = 1
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[2];
rz(-0.786699406177) q[2];
mcx q[0], q[1], q[2];
rz(0.786699406177) q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
ccUHdg q[0], q[1], q[3], q[4];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[2];
rz(1.69312841976) q[2];
mcx q[0], q[1], q[2];
rz(-1.69312841976) q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
ccUH q[0], q[1], q[3], q[4];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[2];
rz(1.69312841976) q[2];
mcx q[0], q[1], q[2];
rz(-1.69312841976) q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
ccUHdg q[0], q[1], q[3], q[4];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[2];
rz(0.784096920618) q[2];
mcx q[0], q[1], q[2];
rz(-0.784096920618) q[2];
mcx q[0], q[1], q[3];
mcx q[0], q[1], q[3], q[2];
mcx q[0], q[1], q[3];

// extract (C - Cdag)/(2i) on the component selector
z q[1];
h q[1];
rz(3.14159265359) q[1];

// combine 1/2 * (E_cos - i E_sin)
sdg q[0];
h q[0];
rz(6.28318530718) q[0];
