OPENQASM 2.0;
include "qelib1.inc";

opaque UH a0, s0;
opaque UHdg a0, s0;
opaque cUH c, a0, s0;
opaque cUHdg c, a0, s0;
opaque mcx selector, c0, t;

qreg q[5];

// q[0] = Hamiltonian-simulation selector ancilla
// q[1] = QSP imaginary-part extraction selector ancilla
// q[2] = QSP phase ancilla
// q[3] = block-encoding ancilla[0]
// q[4] = system qubit[0]

// Full Hamiltonian simulation QSP block generated by tools/hamsim_qsp.py.
// The outer selector multiplexes the QSP phases: each common layer applies the
// cosine signed phase, then selector |1> adds the sine-cosine phase difference.
// The common U_H/U_Hdg skeleton is shared; only the sine branch has the final
// extra U_H and phase. The component selector extracts pyqsp's imaginary
// response before the outer sdg+h combines P_cos(H) - i P_sin(H).
//
// P_cos(x) = 0.49999966355545339 - 0.062493938728279574*x^2 + 0.0012858918109143005*x^4
// P_sin(x) = 0.24999991579484243*x - 0.010415992523176125*x^3 + 0.00012885803586171963*x^5
// Expected all-zero selector branch = 0.24999983177772669 - 0.12499995789742122*i*x - 0.031246969364139787*x^2 + 0.0052079962615880623*i*x^3 + 0.00064294590545715025*x^4 - 6.4429017930859816e-05*i*x^5
//
// QSP phases:
//   cos phi_0 = 9.1052521925845284e-05
//   cos phi_1 = -0.017336228154365477
//   cos phi_2 = 0.48874382575306075
//   cos phi_3 = -0.017336228154365477
//   cos phi_4 = 9.1052521925845284e-05
//   sin phi_0 = 4.0876887309541981e-06
//   sin phi_1 = -0.0013011822987092736
//   sin phi_2 = 0.1223320925366167
//   sin phi_3 = 0.1223320925366167
//   sin phi_4 = -0.0013011822987092736
//   sin phi_5 = 4.0876887309541981e-06

h q[0];
h q[1];

// common phase 0
// cos phi_0 = 9.10525219258e-05
// cos psi_0 = 0.785489215919
// sin phi_0 = 4.08768873095e-06
// sin psi_0 = 0.785402251086
// Delta_0 = sin psi_0 - cos psi_0 = -8.69648331949e-05
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(0.785489215919) q[2];
cx q[3], q[2];
rz(-0.785489215919) q[2];
cx q[3], q[2];
x q[3];

rz(-0.785489215919) q[2];
cx q[3], q[2];
rz(0.785489215919) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(8.69648331949e-05) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-8.69648331949e-05) q[2];

mcx q[0], q[1], q[2];

rz(-8.69648331949e-05) q[2];

mcx q[0], q[1], q[2];

rz(8.69648331949e-05) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U
UH q[3], q[4];

// common phase 1
// cos phi_1 = -0.0173362281544
// cos psi_1 = 1.55346009864
// sin phi_1 = -0.00130118229871
// sin psi_1 = 1.5694951445
// Delta_1 = sin psi_1 - cos psi_1 = 0.0160350458557
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(1.55346009864) q[2];
cx q[3], q[2];
rz(-1.55346009864) q[2];
cx q[3], q[2];
x q[3];

rz(-1.55346009864) q[2];
cx q[3], q[2];
rz(1.55346009864) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.0160350458557) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.0160350458557) q[2];

mcx q[0], q[1], q[2];

rz(0.0160350458557) q[2];

mcx q[0], q[1], q[2];

rz(-0.0160350458557) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U^\dagger
UHdg q[3], q[4];

// common phase 2
// cos phi_2 = 0.488743825753
// cos psi_2 = 2.05954015255
// sin phi_2 = 0.122332092537
// sin psi_2 = 1.69312841933
// Delta_2 = sin psi_2 - cos psi_2 = -0.366411733216
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(2.05954015255) q[2];
cx q[3], q[2];
rz(-2.05954015255) q[2];
cx q[3], q[2];
x q[3];

rz(-2.05954015255) q[2];
cx q[3], q[2];
rz(2.05954015255) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.366411733216) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.366411733216) q[2];

mcx q[0], q[1], q[2];

rz(-0.366411733216) q[2];

mcx q[0], q[1], q[2];

rz(0.366411733216) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U
UH q[3], q[4];

// common phase 3
// cos phi_3 = -0.0173362281544
// cos psi_3 = 1.55346009864
// sin phi_3 = 0.122332092537
// sin psi_3 = 1.69312841933
// Delta_3 = sin psi_3 - cos psi_3 = 0.139668320691
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(1.55346009864) q[2];
cx q[3], q[2];
rz(-1.55346009864) q[2];
cx q[3], q[2];
x q[3];

rz(-1.55346009864) q[2];
cx q[3], q[2];
rz(1.55346009864) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.139668320691) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.139668320691) q[2];

mcx q[0], q[1], q[2];

rz(0.139668320691) q[2];

mcx q[0], q[1], q[2];

rz(-0.139668320691) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// common U^\dagger
UHdg q[3], q[4];

// common phase 4
// cos phi_4 = 9.10525219258e-05
// cos psi_4 = 0.785489215919
// sin phi_4 = -0.00130118229871
// sin psi_4 = 1.5694951445
// Delta_4 = sin psi_4 - cos psi_4 = 0.784005928577
// base cos signed phase
x q[1];
cx q[1], q[2];
x q[1];

x q[3];
rz(0.785489215919) q[2];
cx q[3], q[2];
rz(-0.785489215919) q[2];
cx q[3], q[2];
x q[3];

rz(-0.785489215919) q[2];
cx q[3], q[2];
rz(0.785489215919) q[2];
cx q[3], q[2];

x q[1];
cx q[1], q[2];
x q[1];

// extra signed difference phase on sin branch only
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.784005928577) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.784005928577) q[2];

mcx q[0], q[1], q[2];

rz(0.784005928577) q[2];

mcx q[0], q[1], q[2];

rz(-0.784005928577) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

// sin-only final U
cUH q[0], q[3], q[4];

// final sin-only phase 5
// sin phi_5 = 4.08768873095e-06
// sin psi_5 = -0.785394075709
x q[3];
mcx q[3], q[0], q[2];
x q[3];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(0.785394075709) q[2];

x q[1];
mcx q[1], q[0], q[2];
x q[1];

rz(-0.785394075709) q[2];

mcx q[0], q[1], q[2];

rz(-0.785394075709) q[2];

mcx q[0], q[1], q[2];

rz(0.785394075709) q[2];

x q[3];
mcx q[3], q[0], q[2];
x q[3];

h q[1];
sdg q[1];
x q[1];

sdg q[0];
h q[0];
